default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: username # edit me
  password: password # edit me
  timeout: 5000
  host: localhost
  port: 5432

development:
  <<: *default
  database: ipay_development

test:
  <<: *default
  database: ipay_test

production:
  <<: *default
  database: ipay_production
